### ISSUE TITLE
Font clipping problem

### ISSUE THREAD

**Issue by themackey5** [raysfire/rayshud#192]
For me when using this HUD it appears that texts are cut off right at the bottom of the line.

It's barely visible in all caps:
![hud font question 01](https://user-images.githubusercontent.com/105122314/167263919-7065a6a6-2d35-47d2-b1f5-b1d5feb98b82.JPG)

But when there are small letters like y for example it's pretty obvious:
![hud font question 02](https://user-images.githubusercontent.com/105122314/167263921-a748356b-8368-43b3-bf9b-54002c1b922f.JPG)

Haven't found anything related after a quick search, any idea what could be causing this?

Using the latest rayshud release on windows 10 with mastercomfig

**Comment by CriticalFlaw** [comment]
Which operating system and resolution are you using? This used to be a bigger issue in earlier versions of rayshud but has been fixed over time and I had not been able to reproduce it on my side.
![image](https://user-images.githubusercontent.com/6818236/179124883-4eaa8ea1-6cae-41f9-9558-648374b84076.png)

**Comment by themackey5** [comment]
I'm using the most recent Windows 10 version with a resolution of 1920 x 1080 in a noborder window. Most recent version of rayshud is installed as well. Just completely cleared my custom folder and launch options but the problem remains.

**Comment by CriticalFlaw** [comment]
In your example for the Eyelander - where was that screenshot taken?

**Comment by themackey5** [comment]
It was taken while viewing the backpack. The same behaviour is noticed while viewing basically any other page of the main menu as well though. killfeed and killcams are also affected.

**Comment by CriticalFlaw** [comment]
I suspect it may be possible that an incorrect version of the font is being used by the HUD. It may be possible that Cerbetica is already installed and it's causing issues. Try installing the fonts that are located in `rayshud/resource/fonts` and try again.

**Comment by themackey5** [comment]
That actually did fix it. Thanks a lot!

**Comment by CriticalFlaw** [comment]
Awesome! Thanks and Happy Holidays.
